### ISSUE TITLE
Check for missing specs (all/exported_only)

### ISSUE THREAD

**Issue by robertoaloi** [inaka/elvis_core#144]
The Inaka Guidelines contain a [write-function-specs](https://github.com/inaka/erlang_guidelines#write-function-specs) rule, but the rule is not implemented as a check.

Even if an [undocumented compiler option exists](https://stackoverflow.com/questions/12092682/warnings-for-functions-without-type-specs) to warn about missing specs, this is not ideal for big, existing code bases which use it in combination with the "warning as errors" option.

It would be nice to have an Elvis check for missing specs, ideally with an option to check only exported functions / all functions.

**Comment by elbrujohalcon** [comment]
I'm closing this one. I don't see us implementing this in the near future, @paulo-ferraz-oliveira. Feel free to reopen it if you plan to work on it.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... yeah. Since the compiler already has this as an option, somehow, I'm not sure repeating it in `elvis_core` wouldn't do more "damage" than not.
