### ISSUE TITLE
New rule: avoid blocks expressions

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#147]
Definition: [Block Expressions](https://erlang.org/doc/reference_manual/expressions.html#block-expressions).

**Reasoning**: Use functions… with names… don’t be shy! (by @elbrujohalcon)

Also, we should support `ignore` as we do for other rules (let's just hope `ignore` is already generalized once we get here 😉).

**Comment by paulo-ferraz-oliveira** [comment]
If https://github.com/erlang/eep/blob/master/eeps/eep-0049.md gets implemented our rules loses relevance. Should we still go ahead and keep this Issue?

**Comment by elbrujohalcon** [comment]
Yeah… that EEP is not going to be implemented anytime soon.

**Comment by paulo-ferraz-oliveira** [comment]
This is implemented (locally). I'm just missing adding some tests...
