### ISSUE TITLE
Extend naming conventions with things to avoid

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#151]
Currently, our naming convention rules only allow for a single regex that identifies what is _permitted_/_valid_.
It would be nice to add an additional _forbidden_ regex to identify things that are not valid, like function names starting with `do_`.

Ref: WhatsApp/erlfmt#91

**Comment by elbrujohalcon** [comment]
@bormilan the default should be `none` or `undefined` or something that means _nothing_.
As examples of forbidden regexes, you can use… say… `"[0-9]"` if you don't want numbers at all in your… atoms (maybe). Or you can exclude specific words, like `"(is|maybe|do)"`. Or you may want to forbid names ending with an underscore, i.e. `"_$"`. Use whatever expression you want as a regex example, be creative!

**Comment by bormilan** [comment]
Oh, I understand now; the goal is to allow users to specify their `forbidden` cases if they wish, rather than adding specific rules.
Thanks!

**Comment by paulo-ferraz-oliveira** [comment]
... and make it explicit in the doc., as @elbrujohalcon states, that whatever is accepted in `regex` except if it matches `forbidden`.
