### ISSUE TITLE
Rule suggestion: no spaces around # for maps and records

### ISSUE THREAD

**Issue by robertoaloi** [inaka/elvis_core#153]
In Erlang, using spaces before and after the `#` symbol when dealing with maps or records, is valid. Still, it should be discouraged. I believe a rule that would prevent things like this from happening would be a nice addition:

```
Map = #   { this => map}.
Map     #      {}.
```

**Comment by paulo-ferraz-oliveira** [comment]
@robertoaloi, is it possible that the `operator_spaces` rule works here? I know this is not an operator, but just wondering...

**Comment by elbrujohalcon** [comment]
I don't think `operator_spaces` would work, mostly because that rule is a _text-based_ one and I don't think we can implement this without some parsing.
On the other hand, I ❤️  this rule a lot!

**Comment by elbrujohalcon** [comment]
FWIW: Using a formatter takes care of this thing pretty neatly.
