### ISSUE TITLE
map(key, key, ...) on the left side of a pattern and in expressions/right side

### ISSUE THREAD

**Issue by kvakvs** [inaka/elvis_core#156]
Having:
`#{key := A, x := X, y := Y, key := B}` = ZZZ,
on the left of a pattern is not an error but can be very confusing. It could be a warning.

Having it on the right side of a pattern, or in a free-standing expression — is not an error but most likely is a sign of a typo, or a copy-paste error.
`ZZZ = #{key => A, x => xxx, y => yyy, key => B}`

**Comment by elbrujohalcon** [comment]
This is already taken care of by the Erlang compiler. It emits warnings such as…

```erlang
your_module.erl:9:60: Warning: key 'a' will be overridden in expression
%    9|     Other = NewMap#{even := using, different => accessors, a => "arrow", a := "not arrow"},
%     |                                                            ^
```
