### ISSUE TITLE
Rule idea: no `-type`s in .hrl files

### ISSUE THREAD

**Issue by erszcz** [inaka/elvis_core#162]
Defining types in public header files (especially those intended for inclusion via `-include_lib()`) might lead to type name clashes between projects and even modules of a single big project.
Instead, types should be defined in modules which they correspond to (with `-export_type()`) and this way take advantage of the namespacing offered by module names.
In other words, "no type definitions in header files" rule means that we will always need to use `some_mod:some_type()` unless referring to a type from the same module it's defined in.

**Comment by paulo-ferraz-oliveira** [comment]
Another good one.

**Comment by elbrujohalcon** [comment]
We should split `hrl_files` from `erl_files` ruleset… Which is something we should've done already a long time ago anyway :)

**Comment by paulo-ferraz-oliveira** [comment]
There's not many `hrl`-specific rules, at the moment, are there? In any case, I agree, it's a good suggestion. It can be breaking, however, but we can always add a warning and keep current behaviour and break when we have enough stuff to go to 2.x
