### ISSUE TITLE
Function purity checks 

### ISSUE THREAD

**Issue by igaray** [inaka/elvis_core#168]
Explore some solution to explicitly mark functions as pure, .i.e. with no side effects, possibly with %% @pure comments, to have elvis check that the funcion does not access impure functions, ets tables, send or receive messages, access a database, etc.

Alternatively, have elvis warn about all impure functions, and explitly mark impure functions to suppress warnings.

Or enable both modes.

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon: I'm now wondering if this is beyond the scope of `elvis`.

**Comment by jfacorro** [comment]
>  I'm now wondering if this is beyond the scope of elvis.

IMHO I think it is beyond what Elvis should report on.

**Comment by paulo-ferraz-oliveira** [comment]
Me too. Shall we close it? It's around 6 years old 😄

**Comment by elbrujohalcon** [comment]
And closed… it is!

**Comment by paulo-ferraz-oliveira** [comment]
You `hank`ed it.
