### ISSUE TITLE
Consider more default operator spaces

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#172]
(don't want to get into an argument about what is an operator or not 😄)

Should we consider defaults for these?

```erlang
=
+
-
*
/
%
<
=<
>
>=
==
=:=
/=
=/=
--
=>
:=
<-
<=
||
|
::
->
```

**Comment by elbrujohalcon** [comment]
I like it! I would include all of them in the default, except for `)` and `(`. Those sometimes may require spaces around them, yet sometimes not (I think).

**Comment by paulo-ferraz-oliveira** [comment]
Cool. I've update the previous list by removing `(` and `)`. It's always a choice to add them in the future, I guess (either as default or on the consumer).

**Comment by paulo-ferraz-oliveira** [comment]
Linked to #234, it seems.

**Comment by elbrujohalcon** [comment]
Also, `%` is not an operator.

**Comment by paulo-ferraz-oliveira** [comment]
> Also, `%` is not an operator.

I wanted to make sure you were paying attention 🤣 (seriously, though, I don't know where that one came from).
