### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#188]
The new fixes in `master` _deserve_ a new release. I hereby politely request one 😄 

**Edit**: ah, and I also politely request it to be published to Hex.pm. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Also, I need it for https://github.com/inaka/cowboy-trails/pull/97.

**Comment by elbrujohalcon** [comment]
https://hex.pm/packages/elvis_core/1.1.2

**Comment by paulo-ferraz-oliveira** [comment]
Thanks much.
