### ISSUE TITLE
Output line as first element in warning

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#190]
As is, messages are of type `Atom "<Atom>" on line <Line> does not...`.

I'm wondering if it would be best to make the output uniform, where possible (not all outputs have a line), like e.g.

`<Line>: Atom "<Atom>" does not...`

**Comment by elbrujohalcon** [comment]
Yeah… like…

```
path/to/module.erl:123: Atom "blEh" does not…
```

**Comment by paulo-ferraz-oliveira** [comment]
Oh, that's even a step further. We usually group the output per file (file's the "header" of the output section), but if you prefer we can stop doing that.

**Comment by paulo-ferraz-oliveira** [comment]
I believe `{output_format, parsable}` already takes care of this, either partially or completely.
