### ISSUE TITLE
Print initial message, upon starting analysis

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#193]
When analysis take too long, it's nice to have something like a waiting message, so we know the system's not stuck.

```erlang
elvis analysis starting, this may take a while...
```

(it's basically the same message as `rebar3 dialyzer` already outputs, in another scope).

@elbrujohalcon, I feel this makes more sense here, but if you prefer I can transfer the issue over to `rebar3_lint and implement only at the plugin level.

**Comment by elbrujohalcon** [comment]
I think it would fit better in `rebar3_lint`, for 2 reasons:
1 - *nix commands don't usually _introduce_ themselves
2 [and much more important] - it would be easier to implement in a way that respects the style of rebar3 output.

**Comment by paulo-ferraz-oliveira** [comment]
Cool. Are you able to transfer this issue? If not, I can just copy it there. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Oh... I'll copy, then. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Superseded by the above mention.
