### ISSUE TITLE
Handle Windows newlines gracefully

### ISSUE THREAD

**Issue by g-andrade** [inaka/elvis_core#205]
## Bug Description

Recently I tried to run CI for [my lib](https://github.com/g-andrade/locus/) on Windows.

All the tests passed (surprisingly!) but Elvis (invoked through `rebar3_lint`) complained _a lot_ about trailing spaces and operator spaces. Like, [for almost every line of code](https://github.com/g-andrade/locus/runs/3456877027?check_suite_focus=true).

So, what's happening is: `git` can be configured to [automatically convert line endings into whatever the OS's native ones are](https://git-scm.com/book/it/v2/Customizing-Git-Git-Configuration#_core_autocrlf).

And that's what it does by default on the Windows image I used, apparently.

However, `elvis_core` only knows how to split lines using `\n` (e.g. [here](https://github.com/inaka/elvis_core/blob/1.2.0/src/elvis_utils.erl#L45), which leaves all of those extra `\r` around (and they qualify as whitespace.)

## To Reproduce

Now that's tricky :thinking: I don't have Windows myself. 

But it boils down to:
1) clone a rebar3 project which integrates `rebar3_lint` on Windows, and
2) run `rebar3 lint`.

Alternatively, leveraging GitHub Actions for CI'ing on Windows should be enough to confirm the problem.

## Expected Behavior

I expected that any newline-affected rules (e.g. `no_trailing_whitespace`) would take into account Windows newline endings gracefully (`\r\n` rather than just `\n`.)

## `rebar3` Logs

[Here it is](https://github.com/g-andrade/locus/runs/3456877027?check_suite_focus=true) (let me know if more details are needed.)

## Additional Context

 - OS: Microsoft Windows Server 2019 (10.0.17763)
 - Erlang version: OTP 24.0.5 
 - rebar3 version: 3.16.1
 - `rebar3_lint` version: 0.5.0 (which imports `elvis_core` 1.2.0)

**Comment by g-andrade** [comment]
By the way: in the process of investigating the issue I pretty much fixed it, so let me know and I can open a PR.

**Comment by g-andrade** [comment]
[Here's the fix](https://github.com/g-andrade/elvis_core/commit/59d6ee8036cdebf5b8a737c6f76a41133fd52d4a) and here's [confirmation that it worked](https://github.com/g-andrade/locus/runs/3465794759?check_suite_focus=true).

If you agree with the solution, I'll open a PR. 

If not, I'm open to exploring other options (and I'll understand if you don't even consider this a real problem, given how few people are actually using Windows to develop Erlang.)

**Comment by elbrujohalcon** [comment]
@g-andrade Great catch! Amazing description! Incredibly thorough explanation! And spectacular fix!

I would ❤️  to have that as a PR 🙏🏻
