### ISSUE TITLE
New rule (?) behavior vs. behaviour

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#210]
If one of `elvis_core`'s goals is consistency, how about we choose one of:
* behavior
* behaviour
and warn when the other one is used.

eg.
`- behavior(gen_server).` would be Ok
`- behaviour(gen_server).` would warn
or the other way around.

In one of our [rules](https://github.com/inaka/elvis_core/wiki/Rules) we actually already mention "behavior" and not "behaviour", so for consistency...

... or, we could have it disabled by default, but allow consumers to choose one of the forms.

**Comment by elbrujohalcon** [comment]
I vote YES!

And it's a great ticket to be somebody's first contribution to the project.

I'll tag it as `hacktoberfest`. Maybe we get lucky.

**Comment by elbrujohalcon** [comment]
Fixed with #212

**Comment by paulo-ferraz-oliveira** [comment]
> I'll tag it as hacktoberfest. Maybe we get lucky.

Seems we did get lucky 😄
