### ISSUE TITLE
Document numeric_format

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#211]
As implemented by @elbrujohalcon's https://github.com/inaka/elvis_core/pull/209.

I know there's a task there, but it's very easy for it to get lost in history.

**Comment by elbrujohalcon** [comment]
[Done!](https://github.com/inaka/elvis_core/wiki/Rules#numeric-format)

**Comment by paulo-ferraz-oliveira** [comment]
Cool 👍
