### ISSUE TITLE
no_trailing_whitespace detects trailing whitespace on every line for dos-formatted files

### ISSUE THREAD

**Issue by lukebakken** [inaka/elvis_core#220]
To reproduce:

* Using Windows, configure git `core.autocrlf` to be `true` so that files have native (`\r\n`) line endings.
* Clone https://github.com/rabbitmq/ra.git
* Open the `src\ra_app.erl` file in an LSP-enabled editor (neovim in my case)
* Every line is marked as having trailing whitespace:
<img width="927" alt="elvis-trailing-whitespace" src="https://user-images.githubusercontent.com/514926/149239334-11d348fc-eeac-4c3f-94df-305a38e447b5.png">

Workaround is to disable elvis integration in erlang-ls.

Related to: https://github.com/inaka/elvis/pull/215

I'll try to find time to work on this! This may have to with how `erlang_ls` extracts lines:

https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_core/src/els_text.erl#L25-L29

**Comment by elbrujohalcon** [comment]
…aaaand transferred! 🪄 ✨

**Comment by paulo-ferraz-oliveira** [comment]
Windows... nice! 😕 

Should we just ignore `\r` in `elvis_utils:split_all_lines/2` in the case of Windows?

Or is this a Erlang LS "issue", and it should be splitting like we are? @robertoaloi, suggestions?

**Comment by lukebakken** [comment]
> Windows... nice! 😕

Yep, I can't stand apple keyboards and I am debating whether or not to wipe Win 10 and install Arch Linux like my other dev env. For now, I've been making do with Windows.

> Or is this a Erlang LS "issue", and it should be splitting like we are?

I am testing that out now:

https://github.com/erlang-ls/erlang_ls/compare/main...lukebakken:crlf-line-endings

**Comment by lukebakken** [comment]
> Should we just ignore \r in elvis_utils:split_all_lines/2 in the case of Windows?

As @elbrujohalcon pointed out, [`elvis_utils:split_all_lines/2`](https://github.com/inaka/elvis_core/blob/master/src/elvis_utils.erl#L130-L132) already takes `\r\n` into account.

Unfortunately my changes in https://github.com/erlang-ls/erlang_ls/compare/main...lukebakken:crlf-line-endings do not seem to address the issue.

To simplify things, I'm going to take erlang-ls out of the mix and run `elvis` from the command line (if that's possible). I'll report back.

Note, this is *NOT* a big deal because I literally may be the only person trying to do Erlang development on Windows 😉

**Comment by robertoaloi** [comment]
> Or is this a Erlang LS "issue", and it should be splitting like we are? @robertoaloi, suggestions?

From what I understand that was already tried and it didn't work as expected. We have (partially broken) CI for Windows, so it should be possible to implement a simple test case for this and try to replicate it from there. If this is a Windows issue, we should really fix it, since the whole point of the language server is to provide the same experience to users, independently from the OS/editor used.

**Comment by lukebakken** [comment]
> Or is this a Erlang LS "issue", and it should be splitting like we are?

There's a very good chance my changes in https://github.com/erlang-ls/erlang_ls/compare/main...lukebakken:crlf-line-endings are insufficient to address the issue since it's the first time I've looked at that codebase.

I'll do some "`elvis`-only" testing this weekend. If I see this issue, I'll implement the test that @robertoaloi mentions and will see if I can even get the CI fixed.

Thanks for the fast responses and have a nice weekend everyone.

**Comment by lukebakken** [comment]
The issue is there when `elvis` is run standalone. I'll continue investigating!

```
C:\Users\bakkenl\development\rabbitmq\ra [main ≡ +0 ~1 -0 !]> C:\Users\bakkenl\development\inaka\elvis\_build\default\bin\elvis.cmd rock .\src\ra_app.erl
# src/ra_app.erl [FAIL]
  - no_trailing_whitespace
    - Line 1 has 1 trailing whitespace characters.
    - Line 2 has 1 trailing whitespace characters.
    - Line 3 has 1 trailing whitespace characters.
    - Line 4 has 1 trailing whitespace characters.
    - Line 5 has 1 trailing whitespace characters.
    - Line 6 has 1 trailing whitespace characters.
    - Line 7 has 1 trailing whitespace characters.
    - Line 8 has 1 trailing whitespace characters.
    - Line 9 has 1 trailing whitespace characters.
    - Line 10 has 1 trailing whitespace characters.
    - Line 11 has 1 trailing whitespace characters.
    - Line 12 has 1 trailing whitespace characters.
    - Line 13 has 1 trailing whitespace characters.
    - Line 14 has 1 trailing whitespace characters.
    - Line 15 has 1 trailing whitespace characters.
    - Line 16 has 1 trailing whitespace characters.
    - Line 17 has 1 trailing whitespace characters.
    - Line 18 has 1 trailing whitespace characters.
    - Line 19 has 1 trailing whitespace characters.
```

**Comment by lukebakken** [comment]
Hey everyone, turns out there is a simple fix. Check out this diff between 1.1.2 and 1.3.1 of `src/elvis_utils.erl`:

https://github.com/inaka/elvis_core/compare/1.1.2...1.3.1#diff-210652d8f1259c9d4456d891b70a93ae6935476c3f594b72bcf04494d548690a

`elvis` currently depends on `elvis_core` version 1.1.2:

https://github.com/inaka/elvis/blob/master/rebar.config#L66

But `elvis_core` is currently at version `1.3.1`, which has a fix for the CRLF issue.

Any reason why `elvis` is using such an old `elvis_core` version?

Also, note that `erlang_ls` uses `elvis_core` `1.1.1`:

https://github.com/erlang-ls/erlang_ls/blob/main/rebar.config#L13

Looks like some upgrading needs to happen!

**Comment by elbrujohalcon** [comment]
Good catch, @lukebakken.
Let's see if inaka/elvis#565 helps :)

**Comment by paulo-ferraz-oliveira** [comment]
That's why it was strange to us 😄 I did remember @g-andrade had issues using this on Windows, recently, but I didn't read the part where this was being imported by `elvis` thoroughly.

**Comment by elbrujohalcon** [comment]
New version of `elvis` already published to hex.pm: https://hex.pm/packages/elvis

**Comment by paulo-ferraz-oliveira** [comment]
So, should this issue be moved back to `elvis`?

**Comment by lukebakken** [comment]
@elbrujohalcon I'm going to open a PR to update the dep in https://github.com/erlang-ls/erlang_ls. Any gotchas I should be aware of?

**Comment by lukebakken** [comment]
@elbrujohalcon FYI the changes in #565 fix the issue when I run `elvis` locally. Thanks!

**Comment by elbrujohalcon** [comment]
> @elbrujohalcon I'm going to open a PR to update the dep in https://github.com/erlang-ls/erlang_ls. Any gotchas I should be aware of? I'll test it out of course.

No idea. @robertoaloi ?

**Comment by robertoaloi** [comment]
> No idea. @robertoaloi ?

Ideally, we would have a test in Erlang LS which deals with a DOS-formatted file, ensure it fails in the Windows pipeline and passes after the fix.

**Comment by lukebakken** [comment]
@robertoaloi I added a test in #221 that should covers this case. I think after that's merged this issue can be closed.

**Comment by lukebakken** [comment]
Thanks everyone
