### ISSUE TITLE
New Rule: Avoid throw

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#224]
Stemming from [the conversation on the Erlang Forums](https://erlangforums.com/t/should-we-eventually-improve-catch-throw-semantics/1210/6):

> IMO, it is a really bad style, especially in the context of a functional language. It is returning something through side effects. That may have its uses to [quickly break out of deep recursion](https://learnyousomeerlang.com/errors-and-exceptions#try-a-try-in-a-tree), but they are rare. I think I never used throw even once. In any case, I think it should not be made “socially acceptable” to return stuff via throw, much less encouraged.
(said @Maria-12648430)

> I definitely agree. I prefer to use tail-recursive functions instead of non-local returns unless that turns out to be too cumbersome. That is, if the code becomes convoluted written in a tail-recursive way, I will write it in a body-recursive way and use throw to break out of the recursion. I have typically used that in complicated optimization passes in the compiler; that is, the code will do the optimization in recursive functions, but if anything turns up that makes the optimization impossible I will throw a `not_possible` exception to break out of the recursion.
(said @bjorng)

**Comment by paulo-ferraz-oliveira** [comment]
I ❤️ this.
