### ISSUE TITLE
No space after $

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#232]
Don't allow text after (char) character $
Don't forget to validate newline (as that's not a space).

**Comment by elbrujohalcon** [comment]
Actually… the rule should be more like "Use the proper representation of the space character" and it will not deal with spaces… it will just identify the token corresponding to `$ ` and report a warning then and there.

**Comment by paulo-ferraz-oliveira** [comment]
I was confused about your comment, then re-read my proposel. Where I wrote "Don't allow text" I should've written "Don't allow space" (as per the title). I guess I should've re-read it.

**Comment by elbrujohalcon** [comment]
Right… `$ ` is the space character in the same way that `$a` is the `a` character.
It's not like you can put spaces between `$` and the character.
