### ISSUE TITLE
Revisit defaults for rules

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#234]
operator_spaces and no_space: we might want more operators on these ones...

Other rules: are all the ones we want as defaults in the rulesets? (should we add this info to the Wiki, that certain rules aren't executed by default?)

**Comment by paulo-ferraz-oliveira** [comment]
I've revisited `elvis_project` and found nothing to change.

**Comment by paulo-ferraz-oliveira** [comment]
I've revisited `elvis_text_style` and found nothing to change.

**Comment by paulo-ferraz-oliveira** [comment]
`macro_names`' default regex is `[A-Z][A-Z_0-9]+`. Should we propose something that's closer to what's being [discussed for `atom_naming_convention`](https://github.com/inaka/elvis_core/pull/356#discussion_r1759910875), e.g. `^[A-Z]+(_[A-Z0-9]+)*$`?

**Comment by elbrujohalcon** [comment]
My opinions…

Proposals/stuff to discuss:

| Rules | Discussion | Brujo's take
|- |- |- |
| `macro_names` | The default regex is `[A-Z][A-Z_0-9]+`. Should we propose something that's closer to what's being [discussed for `atom_naming_convention`](https://github.com/inaka/elvis_core/pull/356#discussion_r1759910875), e.g. `^[A-Z]+(_[A-Z0-9]+)*$`? | Yes! |
| `operator_spaces` | Should `!` have white space to left/right? And what about `;`? And `{`/`}`? | `!` and `/` - Yes (L and R); `;` - Depends if the author is using comma-first or comma-last… I would not make a rule about it, like we don't have a rule about `,`; `{` and `}` - Same issue, it depends a lot on how the author wants to format its code, I would force any spacing on them |
| `no_space` | Should `.` be part of the list (no space to left)? And what about `;` (same - no space to left)? And `:` (on both sides)? What about `{` (this is probably tricky to get right!); And what about `[`/`]`? And `#`? And `?`? And `-`? | `.`, `;`, `{`, `[` and `]` - Depends on formatting, as I said above. `:` (as long as we can differentiate it from `::`) - yeah… I would avoid spaces around it. `#` and `?` - does it even compile if they have a space to the right? (if so, yeah… they should not have a space after them). `-`… Don't we have a default to add spaces to both sides of it in the previous rule? |
| `function_naming_convention` | Should we propose something that's closer to what's being [discussed for `atom_naming_convention`](https://github.com/inaka/elvis_core/pull/356#discussion_r1759910875), e.g. `^[a-z]+(_[a-z0-9]+)*$`? | Yes |
| `module_naming_convention` | Should we propose something that's closer to what's being [discussed for `atom_naming_convention`](https://github.com/inaka/elvis_core/pull/356#discussion_r1759910875), e.g. `^[a-z]+(_[a-z0-9]+)*(_SUITE)?$`? | Yes |
| `no_debug_call` | Should we add `io:put_chars/1,2`? | Yeah, why not? |

**Comment by paulo-ferraz-oliveira** [comment]
* `macro_names`: Ok
* `operator_spaces`: Ok
* `no_space`: Ok
* `function_naming_convention`: should it be `^[a-z](_?[a-z0-9]+)*$` instead? What's the difference between what we want here and for an atom name?
* `module_naming_convention`: whatever we decide on before (`function_naming_convention`) should be the same with `(_SUITE)?$` at the end, correct?
* `no_debug_call`: Ok

**Comment by elbrujohalcon** [comment]
* `no_space`: here…
```erlang
some_fun() ->
      some:function()
    , some:other_function()
    , …
    .
```
A very strict form of comma-first.

* `function_naming_convention`: Yeah, it's the same `atom_naming_convention`, but `atom_naming_convention` allows for `_SUITE` at the end. That's all.
* `module_naming_convention`: Yeah, it's the same as `function_naming_convention`, but `atom_naming_convention` allows for `_SUITE` at the end. That's all.

**Comment by paulo-ferraz-oliveira** [comment]
> module_naming_convention: Yeah, it's the same as function_naming_convention, but atom_naming_convention allows for _SUITE at the end. That's all.

It also allows for `_SUITE`, which is effectively the name of CT suites, but I got what you mean.
