### ISSUE TITLE
Error: `undef` while applying rules

### ISSUE THREAD

**Issue by albsch** [inaka/elvis_core#237]
The rules `no_trailing_whitespace` and `no_tabs` fail for an empty Erlang module for no obvious reason:

```
❯ rebar3 lint
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling buggy
===> Compiling buggyb
===> elvis analysis starting, this may take a while...
# apps/buggy/src/buggy.erl [FAIL]
Error: 'undef' while applying rule 'no_trailing_whitespace'.
Error: 'undef' while applying rule 'no_tabs'.
===> Linting failed
```

The module in question:

```
❯ cat apps/buggy/src/buggy.erl
```
```erl
-module(buggy).
```

The lint failing can be reproduced here:

https://github.com/albsch/buggy-linting

My expectation would be that the `rebar3 lint` command succeeds. I think it's an `elvis` issue and not an rebar3 lint plugin issue, so I opened an issue here.

**Comment by paulo-ferraz-oliveira** [comment]
Let me check this.

It's one of those edge cases, but we're Ok to include it in the tests.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/albsch/buggy-linting/blob/master/elvis.config#L10 < it's `elvis_text_style`, not `elvis_style`. Use that and it won't crash.

**Comment by paulo-ferraz-oliveira** [comment]
Here you go: https://github.com/inaka/elvis_core/wiki/Rules#no-trailing-whitespace

**Comment by albsch** [comment]
Ah, thank you. It was a very old `elvis.config` and I didn't notice the change to `elvis_text_style`. Thanks again!
