### ISSUE TITLE
New Rule: If a type is a record, it should be either opaque or not exported

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#264]
### Brief Description

If your module defines a record and it also defines a type for it, that type should not be exported/accessible from the outside.

### Should be on by default?

**YES**

### Reasoning

Since the record is defined within the module, nobody from outside the module should _know_ how to build an instance of that record. That means that the type associated with the record should not be _public_.
It can be an opaque type, so that other modules can pass around record instances but not [de]construct them. Or it can just be not exported so no modules other than the current one have knowledge about the record.

#### Examples

```erlang
-module bad.
-record my_rec, {a, b, c}.

-type my_rec() :: #my_rec{}.
-export_type [my_rec/0].
```

```erlang
-module good.
-record my_rec, {a, b, c}.

-opaque my_rec() :: #my_rec{}.
-export_type [my_rec/0].
```

```erlang
-module also_good.
-record my_rec, {a, b, c}.

-type my_rec() :: #my_rec{}.
```

**Comment by paulo-ferraz-oliveira** [comment]
No maps? Or simply **tuples** instead of **records**?

**Comment by paulo-ferraz-oliveira** [comment]
It could even be part of the options: `applies_to: [maps, records, tuples]` where the default would be `records` (and/or tuples too).
