### ISSUE TITLE
New Rule: Export All Used Types

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#265]
### Brief Description

The idea is to emit a warning every time a spec for an exported function uses a _local_ type that's not exported.

### Should be on by default?

**YES**

### Reasoning

If you put a type in a spec of an exported function, that means that people writing modules that call that function should know what that type is and they may as well pass instances of that type around before calling your function. So, to add their own specs, and also to keep dialyzer messages cleaner, they should put `your_mod:your_type()` in their specs, instead of the actual definition of the type.
To be able to do that, the type must be exported.

### Refactoring Proposal

Add the non-exported types to an `-export_type(…).` attribute.

### Examples

```erlang
-module bad.

-type my_type() :: my | type.

-export [my_fun/1].

-spec my_fun(my_type()) -> my_type().
my_fun(my) -> type;
my_fun(type) -> my.
```

```erlang
-module good.

-type my_type() :: my | type.
-export_type [my_type/0].

-export [my_fun/1].

-spec my_fun(my_type()) -> my_type().
my_fun(my) -> type;
my_fun(type) -> my.
```

**Comment by paulo-ferraz-oliveira** [comment]
Oh, yeah, we **ARE** missing this one. ❤️
