### ISSUE TITLE
Consistent Variable Casing

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#266]
### Brief Description

Use the same _casing_ for all variables with the same name within a module. E.g., emit a warning when Elvis finds both `Userid` and `UserId`or `UserID` in a module.

### Should be on by default?

**YES**

### Reasoning

If two variables have the same name, it's very likely that they refer to the same concept and, therefore, it would make the lives of code readers easier if they share the exact same name, including casing and all.

### Refactoring Proposal

Rename one or more of the variables.

### Examples

```erlang
-module bad.

-export [my_fun/1, my_fun/2].

my_fun(MyVar) -> my_fun(MyVar, too).

my_fun(Myvar, too) -> {Myvar, too}.
```

```erlang
-module good.

-export [my_fun/1, my_fun/2].

my_fun(MyVar) -> my_fun(MyVar, too).

my_fun(MyVar, too) -> {MyVar, too}.
```

**Comment by elbrujohalcon** [comment]
Question about the warnings emitted by this function:
If I have the following module…

```erlang
-module(zzinconsistency).

-export([fun1/1, fun2/1, fun3/1, fun4/1]).

fun1(BadVar) -> BadVar.

fun2(BadVAR) -> BadVAR.

fun3(BadVAR) -> BadVAR.

fun4(BADVar) ->
    BADVar.
```

…how would you like the warnings to be reported?

### Option 1: Naïvely
We report each and every occurrence of a variable name with different casing.
The problem is that all occurrences of each variable are shown. So, for instance, `BADVar` is reported in both line 11 (where it's defined) and line 12 (where it's used).

```erlang
# src/zzinconsistency.erl [FAIL]
  - consistent_variable_casing (https://github.com/inaka/elvis_core/tree/main/doc_rules/elvis_style/consistent_variable_casing.md)
    - Variable BadVar (in line 5) is also written as BadVAR in line 7.
    - Variable BadVar (in line 5) is also written as BadVAR in line 7.
    - Variable BadVar (in line 5) is also written as BadVAR in line 9.
    - Variable BadVar (in line 5) is also written as BadVAR in line 9.
    - Variable BadVar (in line 5) is also written as BADVar in line 11.
    - Variable BadVar (in line 5) is also written as BADVar in line 12.
```

### Option 2: Just the first time for each var
We report just one instance of each different casing. This will avoid repeating the same var name for all the places in which a variable is used, but… if two different functions have the same "miscased" variable name, only the first one will be reported. And those are technically two different variables. Solving this to report **each variable once** it's close to impossible (we need to handle variable scoping rules and I wouldn't do that in Elvis).

```erlang
# src/zzinconsistency.erl [FAIL]
  - consistent_variable_casing (https://github.com/inaka/elvis_core/tree/main/doc_rules/elvis_style/consistent_variable_casing.md)
    - Variable BadVar (in line 5) is also written as BadVAR in line 7.
    - Variable BadVar (in line 5) is also written as BADVar in line 11.
```

### Option 3: One line for each miscased variable
We report just one instance of each **variable** with a list of the different ways in which it's written (but without the individual line numbers). This option is more compact, but it provides less information.

```erlang
# src/zzinconsistency.erl [FAIL]
  - consistent_variable_casing (https://github.com/inaka/elvis_core/tree/main/doc_rules/elvis_style/consistent_variable_casing.md)
    - Variable BadVar (in line 5) is written with other casings through the module: [BadVAR, BADVar].
```

Personally, I prefer the option 3, but let me know what you think.

**Comment by paulo-ferraz-oliveira** [comment]
I'd probably go with option 3, too.
