### ISSUE TITLE
Find More Rules!

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#281]
Let's check other linters, find their list of rules/guidelines and ~copy~ use them for inspiration 🙄

**Comment by elbrujohalcon** [comment]
Reference: https://github.com/caramelomartins/awesome-linters

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, since I started using Credo I got inspired by some of its rules. I'll try to list them below so we can discuss further.

**Comment by elbrujohalcon** [comment]
Feel free to do it, but keep in mind that I'm currently (during working hours) going over that list myself and adding the ones that I find useful/interesting as tickets in the 3.0.0 milestone.

**Comment by paulo-ferraz-oliveira** [comment]
Credo.Check.Consistency.LineEndings
Credo.Check.Warning.UnsafeToAtom
Credo.Check.Warning.LeakyEnvironment
Credo.Check.Warning.BoolOperationOnSameValues
Credo.Check.Refactor.Apply
Credo.Check.Readability.TrailingBlankLine
Credo.Check.Readability.StrictModuleLayout
Credo.Check.Readability.RedundantBlankLines
Credo.Check.Readability.PreferUnquotedAtoms
Credo.Check.Readability.LargeNumbers

**Comment by paulo-ferraz-oliveira** [comment]
I've recently (for work too) gone over that list for all rules. I'm convinced that (from Credo) Elvis shouldn't be missing much more than the ones listed above.

**Comment by elbrujohalcon** [comment]
I'll review your list as well tomorrow.

**Comment by elbrujohalcon** [comment]
Let's go through your list, @paulo-ferraz-oliveira …

* Credo.Check.Consistency.LineEndings: While I have no problem adding such a rule, I would argue that this is a _formatter_ issue. It won't be a priority for me.
* Credo.Check.Warning.UnsafeToAtom: This can be achieved already using a clever configuration for [No Call](https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/no_call.md). Besides, I think this rule fits more nicely in a tool like PEST than Elvis.
* Credo.Check.Warning.LeakyEnvironment: This one seems interesting, but I'm not sure how it's implemented / what's the algorithm for it. Also, I think this one fits better in PEST than here.
* Credo.Check.Warning.BoolOperationOnSameValues: This is a great one! I'll write a ticket for it.
* Credo.Check.Refactor.Apply: This can be achieved already using a clever configuration for [No Call](https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/no_call.md).
* Credo.Check.Readability.TrailingBlankLine: While I have no problem adding such a rule, I would argue that this is a _formatter_ issue. It won't be a priority for me.
* Credo.Check.Readability.StrictModuleLayout: A really nice rule. Not trivial to implement because it has to be as configurable as the one in Credo, but I'll write a ticket for it nonetheless.
* Credo.Check.Readability.RedundantBlankLines: While I have no problem adding such a rule, I would argue that this is a _formatter_ issue. It won't be a priority for me.
* Credo.Check.Readability.PreferUnquotedAtoms: While I have no problem adding such a rule, I would argue that this is a _formatter_ issue. It won't be a priority for me.
* Credo.Check.Readability.LargeNumbers: We already have [Numeric Format](https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/numeric_format.md). I think we've got this one covered.

**Comment by elbrujohalcon** [comment]
I'm still going through the whole list of rules… I'll pick the ones I would like to have in Elvis and turn them into tickets, including `Credo.Check.Warning.BoolOperationOnSameValues`, `Credo.Check.Warning.BoolOperationOnSameValues`, and `Credo.Check.Readability.StrictModuleLayout`

**Comment by paulo-ferraz-oliveira** [comment]
For the ones that are "formatter" issues we could still have the issues created for `elvis` and they might be picked up; we already have some (implemented and released) that are "formatter"-based, anyway :)

As for LargeNumbers, yeah, I forgot to remove it when doing the second review on my list.

Agree for everything else.

**Comment by elbrujohalcon** [comment]
Yeah, @paulo-ferraz-oliveira ! Do create the issues that are formatter-related, of course! Just don't put them on the `3.0.0` milestone ;)
