### ISSUE TITLE
Max Function Arity

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#286]
### Brief Description

Warn if a function has too many arguments.

### Should be on by default?

**YES**

### Options

-  `max_arity :: pos_integer()` (default: `5`)

**Note:** I picked `5` as the default basically randomly. If the implementor can do a proper analysis of some public Erlang codebases to determine what a _reasonable_ default should be, much better.

### Reasoning

Quoting from Credo docs:
> A function can take as many parameters as needed, but even in a functional language, there can be too many parameters.

### Origin (#281)

Inspired by the `Refactor.FunctionArity` rule from [Credo](https://hexdocs.pm/credo/Credo.Check.Refactor.FunctionArity.html)

**Comment by maco** [comment]
Credo's default is 8. I don't really see why not have the same default.

**Comment by paulo-ferraz-oliveira** [comment]
8 sounds reasonable as a default. In a team I used to work in we had 7 as a "rule of thumb" 👍 Then you had to use maps or records, or otherwise work around it :) Most of the initial cases it was just people adding options as new arguments :)

**Comment by elbrujohalcon** [comment]
`8` is a great number, yes!
