### ISSUE TITLE
New rule: No Single Clause Case Statements

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#290]
### Brief Description

The following code…

```erlang
case do:something() of
    {ok, Result} -> do:something(else)
end
```

…should actually be written using pattern-matching:

```erlang
{ok, Result} = do:something(),
do:something(else)
```

The `case` statement is unnecessary and the only difference between the two is that the exception raised in the case of error changes from `case_clause` to `badmatch`.

### Should be on by default?

**YES**

### Options

- None.

### Reasoning

Paraphrasing Elm-Review documentation:

> […] single-pattern case expressions […] may be written more concisely or removed entirely.

### Origin (#281)

Inspired by the `NoSinglePatternCase` rule from [elm-review](https://package.elm-lang.org/packages/SiriusStarr/elm-review-no-single-pattern-case/1.0.1/NoSinglePatternCase)

**Comment by paulo-ferraz-oliveira** [comment]
Should there be an equivalent to `maybe`?
