### ISSUE TITLE
Drop support for OTP versions below 23.

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#303]
Basically set `minimum_otp_version` to `23` and remove all the `-if(?OTP_RELEASE >= 23).` switches from everywhere.

**Comment by paulo-ferraz-oliveira** [comment]
We should probably think about adding a badge to the README, but I'm not sure how easily maintainable that'll be.

**Comment by paulo-ferraz-oliveira** [comment]
e.g. `rebar3` has this
<img width="221" alt="image" src="https://user-images.githubusercontent.com/7303768/222425447-2596d0ca-a8b2-4388-95c9-09e32dbe840c.png">
