### ISSUE TITLE
Broken README links

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#307]
## Bug Description

Broken links, from README:
* https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/no_space_after_pount.md
* https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/operator_spaces.md

## To Reproduce

Go to README.md; try to open the links.

## Expected Behavior

Links are valid.

**Comment by paulo-ferraz-oliveira** [comment]
pount > pound should fix the first one
the second one we'll have to create an .md for.

**Comment by DenysGonchar** [comment]
There was documentation for `operator_spaces`, but for some unknown reason it's removed:
https://github.com/inaka/elvis_core/commit/f322bd55648f2823c67707a3c5d106d1bc0c07f0

unfortunately PR https://github.com/inaka/elvis_core/pull/272 doesn't provide any explanation.

**Comment by elbrujohalcon** [comment]
Good catch, @DenysGonchar … It was very likely a mistake (from my part) to remove that file.
