### ISSUE TITLE
Add option to ignore non-exported functions on max_function_arity

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#309]
## Is your feature request related to a problem? Please describe

_Private_ functions having too many arguments are not as much of a problem as exported ones. They should not be judged too severely.

## Describe the solution you'd like

I would add a parameter like…

* `non_exported_max_arity :: pos_integer()`

…with a very very large default value (e.g. `20`)

## Describe alternatives you've considered

An alternative would be to just ignore non-exported functions or have a flag like `apply_to :: exported | non_exported | both` that defaults to `exported`. But I think my proposal above is more flexible.

**Comment by bormilan** [comment]
I don't know which one is better, but from the name of the issue, I assume that you want to add the ignoring version first based on @elbrujohalcon's alternative idea.

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, we seem to want `non_exported_max_arity`.
