### ISSUE TITLE
Unused Variable Names

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#310]
### Name

`unused_variable_names`

### Brief Description

Erlang allows us to use `_` as a name for variables that are not meant to be used. But it’s a common practice to give these variables meaningful names anyway (`_user` instead of `_`).

### Reasoning

It eases code readability.

### Refactoring Proposal

Name your anonymous variable meaningfully.

### Origin

Inspired by Credo's [Credo.Check.Consistency.UnusedVariableNames](https://hexdocs.pm/credo/Credo.Check.Consistency.UnusedVariableNames.html).

**Comment by elbrujohalcon** [comment]
I don't mind implementing this rule, but I would not want it to be on by default.
I'm a proud member of the _Do not use ignored variables_ team.
Using `_Something` has more often than not led me to inconsistencies and unwanted pattern-matching scenarios. I prefer good specs/docs for readability and `_` if you need to ignore something.

**Comment by paulo-ferraz-oliveira** [comment]
The goal is not to use the variable, if it's anonymous 😓 (maybe my description is not accurate): I think the compiler even complains about this, and [we have a rule for it](https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/used_ignored_variable.md).

The goal is to have it named, instead of just `_`, if it's present. It's not just the specs, either.

Stuff like

```erlang
case op() of
  {ok, Result} -> ...
  _ -> ...
end
```

is, more often than not (to me) unreadable.

Yes, I also agree it shouldn't be on by default.

**Comment by elbrujohalcon** [comment]
The goal is not to use it and there is a rule for that, but… what happened to me more times than the ones I want to admit is this…

```erlang
case something() of
    {ok, AThing} -> …
    {error, _Reason} -> …
end,
…several lines more…
case something:else() of
    {ok, OtherThing} -> …
    {error, _Reason} -> 💥
end
…
```

**Comment by elbrujohalcon** [comment]
In my mind…

```erlang
case op() of
    {ok, Result} -> …
    _ -> ignored_error
end.
```

…is not really that different than…

```erlang
case op() of
    {ok, Result} -> …
    _IgnoredError -> ignored_error
end.
```

**Comment by paulo-ferraz-oliveira** [comment]
> …is not really that different than…

Yes, in such a simple scope, not really that different, but there's instances where you have many more occurrences, and it gets confusing. I'll close this for now, since it doesn't seem that relevant. Glad there was discussion around it 😄
