### ISSUE TITLE
New rule: consistent file names

### ISSUE THREAD

**Issue by kivra-pauoli** [inaka/elvis_core#322]
### Name

`consistent_filename`

### Brief Description

Go through projects folders and check if files in them (`*.erl`, and `*.hrl`) are prefixed with the application's name.

This can be a best effort (maybe not good to have it by default):
* get the app name from `.app.src`
* go over `rebar.config` to figure out which folders we should look at (recursively)

As an example, all files in `elvis_core` should start with `elvis_core_`. (they don't, so this makes me thing we could also have an option on the filename suffix to consider...

### Reasoning

Erlang/OTP has no namespacing facilities, this practice is kinda standard and it makes for easier reading.

### Refactoring Proposal

This is probably not good for big existing projects, as it would imply changing file names and their references, but for smaller/newer projects it would be valuable.

**Comment by elbrujohalcon** [comment]
I don't think we need this rule. People can just configure [module_naming_convention](https://github.com/inaka/elvis_core/blob/main/doc_rules/elvis_style/module_naming_convention.md) appropriately.

**Comment by kivra-pauoli** [comment]
Ok. I was just thinking this could go further (and be more _automatic_), because we'd be reading from `.app.src` (and not having to tweak that rule) as well as understanding the paths from `rebar.config` 👍 Otherwise instead of potentially using "_strict", in the future, all projects are forced to define their own override for this...
