### ISSUE TITLE
Rule: Do not use lists on start_link/3,4 and init/1

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#329]
### Name

# No Init Lists

### Brief Description

The idea is to avoid code like this one…

```erlang
-module my_server.
% …exports and everything else…
start_link(AParam) ->
  gen_server:start_link(?MODULE, [AParam], []).

init([AParam]) ->
  …
```

### Reasoning

See [this thread in the forums](https://erlangforums.com/t/args-in-gen-init-1/3169/5?u=elbrujohalcon)

### Refactoring Proposal

Use maps, tuples, or… if you need to ignore the parameter at all, use an atom like `undefined` or `no_argument`.

**Comment by paulo-ferraz-oliveira** [comment]
Should this be a default rule?

**Comment by elbrujohalcon** [comment]
If I'm the one with the final vote, I say **yes!!** But what do you think?

**Comment by paulo-ferraz-oliveira** [comment]
I'm Ok with that. I think it's otherwise misleading, too.
