### ISSUE TITLE
Count `_to_atom` as common caveats?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [inaka/elvis_core#336]
## Is your feature request related to a problem? Please describe

More of a question... should `_to_atom` functions (when used instead of their `_to_existing_atom` counterparts) count as default common caveats?

## Describe the solution you'd like

Maybe they should/could be considered common caveats?

## Describe alternatives you've considered

None yet.

## Additional Context

Not applicable.

**Comment by elbrujohalcon** [comment]
I don't think Elvis should care about that kind of _security_ issues. That's what [PEST](https://github.com/okeuday/pest) is for.

**Comment by paulo-ferraz-oliveira** [comment]
We now have a searchable issue as reference, in any case... Thanks.
