### ISSUE TITLE
Should `no_macros` consider `LOG_...` as allowed?

### ISSUE THREAD

**Issue by kivra-pauoli** [inaka/elvis_core#337]
## Bug Description

Maybe `no_macros` should consider `LOG_...` (and friends) as allowed (?)

## To Reproduce

Use `logger`'s `LOG_INFO`.

## Expected Behavior

No warnings.

## `rebar3` Logs

Not applicable.

## Additional Context

Not applicable.

**Comment by elbrujohalcon** [comment]
I agree, they should be treated as predefined macros.

**Comment by paulo-ferraz-oliveira** [comment]
Released, in Github, as 3.2.2.

**Comment by paulo-ferraz-oliveira** [comment]
Published, to Hex, as 3.2.2: https://hex.pm/packages/elvis_core/3.2.2
