### ISSUE TITLE
Is rebar3 dependency "git_subdir" tag supported ?

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/elvis_core#342]
### Discussed in https://github.com/inaka/elvis/discussions/581

<div type='discussions-op-text'>

<sup>Originally posted by **netboz** May 22, 2024</sup>
Hi,

In my rebar.config, I have something like this :

`{deps,
 [....
  {opentelemetry_api,
   {git_subdir,
    "http://github.com/open-telemetry/opentelemetry-erlang",
    {branch, "main"},
    "apps/opentelemetry_api"}},
....]).`

Elvis is reporting an error at the head f my source file : 

`'function_clause' while applying rule 'protocol_for_deps_rebar'.Elvis(Config Error)`

I was so wondering if `git_subdir` was supported ( I have found nothing regarding this into the code and googling ).

Thanks for any answer</div>

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, I'm transferring the issue here so I can link it to `elvis_core`'s pr.

If you agree we can probably Hex-publish+GitHub-release `elvis_core` (after pr approve+merge), then update both `rebar3_lint` and `elvis` with the new version.

**Comment by elbrujohalcon** [comment]
Thanks, @paulo-ferraz-oliveira … Yeah, I agree. Can you take care of the _release dance_ this time or do you need me to do it?
