### ISSUE TITLE
line_num = 0 for reported errors

### ISSUE THREAD

**Issue by zsoci** [inaka/elvis_core#346]
## Bug Description

[//]:# no_throw, no_catch_expressions and no_dollar_space reports does not set line_num.

## To Reproduce

[//]:# In VSCODE

## Expected Behavior

[//]:# line_num is set correctly

## Additional Context

- OS: MacOS
- Erlang version 26.2.2
- rebar3 version 3.22.1

**Comment by paulo-ferraz-oliveira** [comment]
This was linked to your pull request (to be auto-closed when that one's merged). Thanks.
