### ISSUE TITLE
`rebar3` dependency "git_subdir" tag not supported for `tag` (rule: `protocol_for_deps`)

### ISSUE THREAD

**Issue by kivra-pauoli** [inaka/elvis_core#370]
## Bug Description

#343 is not complete, in that it doesn't support `tag` where it supports `branch`.

## To Reproduce

Take the test file on that pull request and replace `branch` with `tag`, [here](https://github.com/inaka/elvis_core/pull/343/files#diff-aced31f01c95c48279adfa9de16d8c0f1a43f52f6d5e30ebe37caa3a9ad24158R9).

## Expected Behavior

No function clause.

## `rebar3` Logs

Not applicable.

## Additional Context

- OS: all
- Erlang version: all
- rebar3 version: all

**Comment by paulo-ferraz-oliveira** [comment]
I looked at [`rebar3`'s implementation](https://github.com/erlang/rebar3/blob/main/apps/rebar/src/rebar_app_utils.erl), and also [the documentation](https://rebar3.org/docs/configuration/dependencies/#declaring-dependencies). Most likely I'll also pull request there to update https://github.com/erlang/rebar3/blob/main/rebar.config.sample.

**Comment by paulo-ferraz-oliveira** [comment]
`rebar3` and `rebar3.org` have been pull requested for update. Going to import my knowledge here, now...

**Comment by paulo-ferraz-oliveira** [comment]
@elbrujohalcon, I wonder if the rule should be more permissive and allow for `git://` alongside `https://`.

**Comment by elbrujohalcon** [comment]
> @elbrujohalcon, I wonder if the rule should be more permissive and allow for `git://` alongside `https://`.

I think that's a good idea.
