### ISSUE TITLE
add option for global ignore

### ISSUE THREAD

**Issue by Licenser** [inaka/elvis_core#5]
I'm having the situation that I want to exclude some modules entirely. It are auto generated modules for a lexer and parser and enforcing syntax rules on they would be pointless.

I would like to add a `ignore` rule on the top level, along with `dirs` and `filter` that entirely takes modules out of the check.

If there are no objections to this I'll implement it and open a PR.

**Comment by elbrujohalcon** [comment]
This is a duplicate of inaka/elvis#190.
No objections from here, @Licenser :)
